# .readthedocs.yml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - uv sync --group docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats: all
